version: '3'
services:
 app:
  container_name: docker-XMeme
  restart: always
  build: .
  ports:
   - '8081:8081'
   - '8080:8080'
  links:
   - mongo
  environment:
   - MONGODB_URI='mongodb://mongo:27017/XMeme-api'
 mongo:
  container_name: mongo
  image: mongo
  ports:
   - '27017:27017'
